name: Deploy to Server with PM2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Create deployment archive
        run: |
          # 创建部署目录
          mkdir -p deploy

          # 复制 standalone 构建产物
          cp -r .next/standalone/* deploy/

          # 复制静态文件
          cp -r .next/static deploy/.next/static
          cp -r public deploy/public

          # 复制 package.json（用于 PM2 配置）
          cp package.json deploy/

          # 打包部署文件
          tar -czf app-build.tar.gz -C deploy .
